name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.1.0
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:WhiteMatrixTech/dep-gradle-monorepo.git
          ssh_private_key: ${{ secrets.ssh_private_key }}
