name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:
    inputs:
      service:
        description: 'service'
        required: true

jobs:
  #  build: # make sure build/ci work properly
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - run: npm install
  #      - run: npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    outputs:
      leaf: ${{ steps.change.outputs.leaf }}
      need_ci: ${{ steps.change.outputs.need_ci }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: lwnmengjing/mono-repo-gradle
          path: monorepo
      - name: build
        run: npm install && npm run build && npm run package

      - id: git
        name: self
        uses: ./
        with:
          change-paths: '.github/workflows/test.yaml,common0/settings.gradle,common1/settings.gradle,main.py,service2/settings.gradle'
          ignore-paths: '.git,.github,.idea,.vscode,main.py,a,b'
          workspace: ${{ github.workspace }}/monorepo
      - id: dispatch
        name: self
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ./
        with:
          leaf: ${{ github.event.inputs.service }}
          ignore-paths: '.git,.github,.idea,.vscode,main.py,a,b'
          workspace: ${{ github.workspace }}/monorepo
      - id: change
        run: |
          if [ ${{ github.event_name == 'workflow_dispatch' }} ]
          then
            echo "::set-output name=leaf::${{ steps.dispatch.outputs.leaf}}" 
            echo "::set-output name=need_ci::${{ steps.dispatch.outputs.need_ci}}" 
          else
            echo "::set-output name=leaf::${{ steps.git.outputs.leaf}}" 
            echo "::set-output name=need_ci::${{ steps.git.outputs.need_ci}}" 
          fi

  service:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.outputs.need_ci == true }}
    strategy:
      matrix:
        leaf: ${{ fromJson(needs.test.outputs.leaf) }}
    steps:
      - run: echo ${{ matrix.leaf }}
